"use client";

import "./globals.css";
import Header from "./components/header";
import username from "./components/login-main";
import {
  useContext,
  useState,
  createContext,
  Dispatch,
  SetStateAction,
} from "react";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

interface ContextProps {
  userName: string;
  setUserName: Dispatch<SetStateAction<string>>;
}

export const UserNameContext = createContext<ContextProps>({
  userName: "",
  setUserName: () => {},
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userName, setUserName] = useState("");

  return (
    <html lang="ja">
      <head />
      <body>
        <UserNameContext.Provider value={{ userName, setUserName }}>
          <Header />
          {children}
        </UserNameContext.Provider>
      </body>
    </html>
  );
}
